function BasicContentAssist(a,c,b){this.viewer=new TextViewer(a);this.processor=new ContentAssistProcessor(c);this.content_assist=new ContentAssist(this.viewer,this.processor,b)}function CompletionProposal(a,c,b,e,d){this.str=a;this.offset=c;this.len=b;this.cursor=e;this.additional_info=d||""}
CompletionProposal.prototype={getDisplayString:function(){return this.str.toString()},getAdditionalInfo:function(){return this.additional_info},apply:function(a){a.replaceText(this.str.toString(),this.offset,this.offset+this.len);a.setCaretPos(this.cursor)},toString:function(){return this.str.toString()},toHtml:function(){var a=document.createElement("div");a.className="tx-proposal";a.appendChild(document.createTextNode(this.getDisplayString()));return a}};
function ContentAssist(a,c,b){this.viewer=a;this.options={visible_items:10};this.setProcessor(c);this.setOptions(b);this.popup=tx_utils.createElement("div","tx-ca-popup");this.popup_content=tx_utils.createElement("div","tx-ca-popup-content");this.additional_info=tx_utils.createElement("div","tx-ca-additional-info");this.popup.appendChild(this.popup_content);this.popup.appendChild(this.additional_info);a.getElement().parentNode.appendChild(this.popup);this.processor=null;this.is_visible=!1;this.last_proposals=
[];this.is_hover_locked=!1;this.hover_lock_timeout=null;this.selected_class="tx-proposal-selected";this.selected_proposal=0;c&&this.setProcessor(c);var e=this.popup_content,d=this;this.hidePopup();a.addEvent("modify",function(a){d.showContentAssist(a)});var c=!!window.opera,b=/mac\s+os/i.test(navigator.userAgent),f=c&&b;a.addEvent(c?"keypress":"keydown",function(a){a=tx_utils.normalizeEvent(a);if(d.is_visible)switch(a.keyCode){case 38:d.selectProposal(Math.max(d.selected_proposal-1,0));d.lockHover();
a.preventDefault();break;case 40:d.selectProposal(Math.min(d.selected_proposal+1,e.childNodes.length-1));d.lockHover();a.preventDefault();break;case 13:d.applyProposal(d.selected_proposal);d.hidePopup();a.preventDefault();break;case 27:d.hidePopup(),a.preventDefault()}else if(a.keyCode==32&&(a.ctrlKey&&!f||a.metaKey&&f||a.altKey))d.showContentAssist(),a.preventDefault()});var g=!1;a.addEvent("blur",function(){d.hide_timeout=setTimeout(function(){g||d.hidePopup();g=!1},200)});tx_utils.addEvent(e,"mouseover",
function(a){if(!d.is_hover_locked&&(a=tx_utils.normalizeEvent(a),a=d.searchProposal(a.target)))a=d.findProposalIx(a),a!=-1&&d.selectProposal(a,!0)});tx_utils.addEvent(e,"click",function(a){a=tx_utils.normalizeEvent(a);if(a=d.searchProposal(a.target))a=d.findProposalIx(a),a!=-1&&(d.applyProposal(a),d.hidePopup())});tx_utils.addEvent(e,"mousedown",function(a){a=tx_utils.normalizeEvent(a);a.preventDefault();a.stopPropagation();g=!0;return!1});tx_utils.addEvent(document,"mousedown",function(){d.hidePopup()});
tx_utils.addEvent(this.additional_info,"scroll",function(){d.hideAdditionalInfo()})}
ContentAssist.prototype={setProcessor:function(a){this.processor=a},setOptions:function(a){if(a)for(var c in this.options)this.options.hasOwnProperty(c)&&c in a&&(this.options[c]=a[c])},searchProposal:function(a){do if(tx_utils.hasClass(a,"tx-proposal"))break;while(a=a.parentNode);return a},findProposalIx:function(a){for(var c=-1,b=a.parentNode.childNodes,e=0,d=b.length;e<d;e++)if(b[e]==a){c=e;break}return c},applyProposal:function(a){this.popup_content.childNodes[a]&&this.last_proposals[a].apply(this.viewer)},
showPopup:function(a,c){this.popup.style.display="block";this.popup.style.top=c+"px";this.popup.style.width="";var b=this.viewer.getElement(),a=Math.min(b.offsetLeft+b.offsetWidth-this.popup.offsetWidth,a);this.popup.style.left=a+"px";this.popup.style.width=this.popup_content.offsetWidth+"px";this.is_visible=!0;this.lockHover()},hidePopup:function(){this.popup.style.display="none";this.hideAdditionalInfo();this.is_visible=!1},lockHover:function(){this.hover_lock_timeout&&clearTimeout(this.hover_lock_timeout);
this.is_hover_locked=!0;var a=this;setTimeout(function(){a.is_hover_locked=!1},100)},showContentAssist:function(){if(this.processor){var a=this.processor.computeCompletionProposals(this.viewer,this.viewer.getCaretPos());if(a){var c=0,b=0,e=0;this.popup.style.display="block";tx_utils.emptyElement(this.popup_content);for(var d=0,f=a.length;d<f;d++){var g=a[d].toHtml();this.popup_content.appendChild(g);c=a[d].offset;this.options.visible_items>0&&d<this.options.visible_items&&(b+=g.offsetHeight);e+=g.offsetHeight}e>
b?tx_utils.addClass(this.popup,"tx-ca-popup-overflow"):tx_utils.removeClass(this.popup,"tx-ca-popup-overflow");c=this.viewer.getAbsoluteCharacterCoords(c);this.showPopup(c.x,c.y);this.popup_content.style.height=b?b+"px":"auto";this.last_proposals=a;this.selected_proposal=0;this.selectProposal(this.selected_proposal)}else this.hidePopup()}},showAdditionalInfo:function(a){var c=this.last_proposals[a];if(c&&c.getAdditionalInfo()){var b=this.popup_content.childNodes[a],a=this.additional_info;a.innerHTML=
c.getAdditionalInfo();tx_utils.removeClass(a,"tx-ca-additional-info-left");tx_utils.setCSS(a,{display:"block",top:b.offsetTop-this.popup_content.scrollTop});c=this.viewer.getElement();a.offsetLeft+a.offsetWidth+this.popup.offsetLeft>c.offsetLeft+c.offsetWidth&&tx_utils.addClass(a,"tx-ca-additional-info-left")}},hideAdditionalInfo:function(){tx_utils.setCSS(this.additional_info,{display:"none"})},selectProposal:function(a,c){this.popup_content.childNodes[this.selected_proposal]&&tx_utils.removeClass(this.popup_content.childNodes[this.selected_proposal],
this.selected_class);if(this.popup_content.childNodes[a]){var b=this.popup_content.childNodes[a];tx_utils.addClass(b,this.selected_class);if(!c){var e=b.offsetTop,b=b.offsetHeight,d=this.popup_content.scrollTop,f=this.popup_content.offsetHeight;if(e<d)this.popup_content.scrollTop=e;else if(e+b>d+f)this.popup_content.scrollTop=e+b-f}this.showAdditionalInfo(a)}this.selected_proposal=a}};function ContentAssistProcessor(a){a&&this.setWords(a)}
ContentAssistProcessor.prototype={computeCompletionProposals:function(a,c){for(var b=c-1,e="",d="";b>=0&&this.isAllowedChar(d=a.getChar(b));)e=d+e,b--;for(d=c;d<1E3&&this.isAllowedChar(a.getChar(d));)d++;var f=null,g=this.suggestWords(e);if(g.length)for(var f=[],h=0,i=g.length;h<i;h++){var j=g[h],l=j[0],j=this.completitionProposalFactory(l,c-e.length,d-b-1,c-e.length+l.length,j[1]);f.push(j)}return f},completitionProposalFactory:function(a,c,b,e,d){return new CompletionProposal(a,c,b,e,d)},getActivationChars:function(){return'abcdefghijklmnopqrstuvwxyz!@$"'},
isAllowedChar:function(a){a=String(a);if(!a)return!1;return!/[\.,\?\#%\^\$\(\)\{\}\u00ab\u00bb\n \/]/.test(a)},setWords:function(a){for(var c={},b=0,e=a.length;b<e;b++){var d=a[b].toString().charAt(0);d in c||(c[d]=[]);c[d].push(a[b])}this.words=c},suggestWords:function(a){var a=String(a),c=[];if(a&&this.words){var b=a.charAt(0),e=a.length;if(b in this.words)for(var b=this.words[b],d=0,f=b.length;d<f;d++){var g=b[d][0].toString();if(g.indexOf("|")!=-1){var h=g.substr(0,g.indexOf("|"));if(a.indexOf(h)!==
0||e<h.length)continue;g=g.replace("|","")}g.indexOf(a)===0&&g.length>e&&c.push([g,b[d][1]])}}return c}};var EventDispatcher=function(){};
EventDispatcher.prototype={buildListenerChain:function(){if(!this.listenerChain)this.listenerChain={};if(!this.onlyOnceChain)this.onlyOnceChain={}},addEventListener:function(a,c,b){if(!c instanceof Function)throw Error("Listener isn't a function");this.buildListenerChain();for(var b=b?this.onlyOnceChain:this.listenerChain,a=typeof a=="string"?a.split(" "):a,e=0;e<a.length;e++)b[a[e]]?b[a[e]].push(c):b[a[e]]=[c]},hasEventListener:function(a){return typeof this.listenerChain[a]!="undefined"||typeof this.onlyOnceChain[a]!=
"undefined"},removeEventListener:function(a,c){if(!this.hasEventListener(a))return!1;for(var b=[this.listenerChain,this.onlyOnceChain],e=0;e<b.length;e++)for(var d=b[e][a],f=0;f<d.length;f++)d[f]==c&&d.splice(f,1);return!0},dispatchEvent:function(a,c){this.buildListenerChain();if(!this.hasEventListener(a))return!1;for(var b=[this.listenerChain,this.onlyOnceChain],e=new CustomEvent(a,this,c),d=0;d<b.length;d++){var f=b[d][a];if(f)for(var g=0,h=f.length;g<h;g++)f[g](e)}this.onlyOnceChain[a]&&delete this.onlyOnceChain[a];
return!0}};function CustomEvent(a,c,b){this.type=a;this.target=c;if(typeof b!="undefined")this.data=b}function LineCacher(a){this.measurer=a;this.width=a.clientWidth;this.lines=[]}
LineCacher.prototype={getLineOffset:function(a,c){if(!a)return 0;for(var b=this.measurer,e=b.clientWidth!=this.width,d=tx_utils.splitByLines(c),f=tx_utils.getCSS(b,["padding-top","padding-bottom"]),f=parseFloat(f["padding-top"])+parseFloat(f["padding-bottom"]),g,h=0,i=0,j=Math.min(d.length,a);i<j;i++){g=d[i];if(e||!this.lines[i]||this.lines[i].text!==g)b.innerHTML=tx_utils.sanitizeString(g||"&nbsp;"),this.lines[i]={text:g,height:b.offsetHeight-f};h+=this.lines[i].height}this.width=b.clientWidth;return h},
reset:function(){this.lines=[]}};var TextViewer=function(a){this.textarea=a;this._measurer=tx_utils.createMeasurer(a);this.updateMeasurerSize();this.dispatcher=new EventDispatcher;this.line_cacher=new LineCacher(this._measurer);var c=-1,b=null,e=this;tx_utils.addEvent(a,"change keyup",function(){var d=a.value;if(d.length!=c||d!==b)e.dispatcher.dispatchEvent("modify"),c=d.length,b=d});tx_utils.addEvent(window,"focus resize",function(){e.updateMeasurerSize()})};
TextViewer.prototype={getSelectionRange:function(){if("selectionStart"in this.textarea)return{start:this.textarea.selectionStart,end:this.textarea.selectionEnd};else if(document.selection){this.textarea.focus();var a=document.selection.createRange();if(a===null)return{start:0,end:this.getContent().length};var c=this.textarea.createTextRange(),b=c.duplicate();c.moveToBookmark(a.getBookmark());b.setEndPoint("EndToStart",c);return{start:b.text.length,end:b.text.length+a.text.length}}else return null},
setSelectionRange:function(a,c){typeof c=="undefined"&&(c=a);var b=this.textarea;"setSelectionRange"in b?b.setSelectionRange(a,c):"createTextRange"in b&&(b=b.createTextRange(),b.collapse(!0),b.moveStart("character",a),b.moveEnd("character",c-a),b.select())},getCaretPos:function(){var a=this.getSelectionRange();return a?a.start:null},setCaretPos:function(a){this.setSelectionRange(a)},getContent:function(){return this.textarea.value},updateMeasurerSize:function(){var a=tx_utils.getCSS(this.getElement(),
["padding-left","padding-right","border-left-width","border-right-width"]);this._measurer.style.width=this.textarea.clientWidth-(parseInt(a["padding-left"])+parseInt(a["padding-right"])+parseInt(a["border-left-width"])+parseInt(a["border-right-width"]))+"px"},getCharacterCoords:function(a){var c=this.getContent(),b=tx_utils.findNewlineBounds(c,a);this._measurer.innerHTML=tx_utils.sanitizeString(c.substring(b.start,a))+"<i>"+(this.getChar(a)||".")+"</i>";a=this._measurer.getElementsByTagName("i")[0];
a={x:a.offsetLeft,y:a.offsetTop};b=tx_utils.splitByLines(c.substring(0,b.start)).length;b=Math.max(0,b-1);c=this.line_cacher.getLineOffset(b,c);tx_utils.emptyElement(this._measurer);return{x:a.x,y:a.y+c}},getAbsoluteCharacterCoords:function(a){a=this.getCharacterCoords(a);return{x:this.textarea.offsetLeft+a.x-this.textarea.scrollLeft,y:this.textarea.offsetTop+a.y-this.textarea.scrollTop}},getChar:function(a){return this.getContent().charAt(a)},getElement:function(){return this.textarea},replaceText:function(a,
c,b){var e=typeof c!="undefined",d=typeof b!="undefined",f=this.getContent();!e&&!d?(c=0,b=f.length):d||(b=c);this.textarea.value=f.substring(0,c)+a+f.substring(b)},addEvent:function(a,c){for(var b=a.split(/\s+/),e=this.getElement(),d=0,f=b.length;d<f;d++)b[d].toLowerCase()=="modify"?this.dispatcher.addEventListener("modify",c):tx_utils.addEvent(e,a,c)},removeEvent:function(a,c){for(var b=a.split(/\s+/),e=this.getElement(),d=0,f=b.length;d<f;d++)b[d].toLowerCase()=="modify"?this.dispatcher.removeEventListener("modify",
c):tx_utils.removeEvent(e,a,c)}};
var tx_utils={init:function(){var a=document.createElement("textarea");a.value="\n";this.newline_char=a.value;this.has_pre_wrap=!a.currentStyle;this.use_w3c=document.defaultView&&document.defaultView.getComputedStyle;this.copy_props="font-family,font-size,line-height,text-indent,padding-top,padding-right,padding-bottom,padding-left,border-left-width,border-right-width,border-left-style,border-right-style".split(",");this.xml_chars={"<":"&lt;",">":"&gt;","&":"&amp;"};this.ua=navigator.userAgent.toLowerCase();
this.line_breaker=this.ua.indexOf("msie 6")===-1?String.fromCharCode(8203):"&shy;"},walkArray:function(a,c,b){if(b)for(var b=0,e=a.length;b<e;b++){if(c.call(a[b],b,a[b])===!1)break}else for(b=a.length-1;b>=0;b--)if(c.call(a[b],b,a[b])===!1)break},trim:function(a){return(a||"").replace(/^(\s|\u00A0)+|(\s|\u00A0)+$/g,"")},hasClass:function(a,c){var b=a.className;return b&&(" "+b+" ").indexOf(" "+c+" ")>=0},toggleClass:function(a,c){this.hasClass(a,c)?this.removeClass(a,c):this.addClass(a,c)},addClass:function(a,
c){var b=[],e=this;this.walkArray(c.split(/\s+/g),function(c,f){f&&!e.hasClass(a,f)&&b.push(f)});b.length&&(a.className+=(a.className?" ":"")+b.join(" "))},removeClass:function(a,c){var b=a.className||"";this.walkArray(c.split(/\s+/g),function(a,c){b=b.replace(RegExp("\\b"+c+"\\b"),"")});a.className=this.trim(b)},emptyElement:function(a){for(;a.firstChild;)a.removeChild(a.firstChild)},addEvent:function(a,c,b){for(var c=c.split(/\s+/),e=0;e<c.length;e++)a.addEventListener?a.addEventListener(c[e],b,
!1):a.attachEvent&&a.attachEvent("on"+c[e],b)},removeEvent:function(a,c,b){for(var c=c.split(/\s+/),e=0;e<c.length;e++)a.removeEventListener?a.removeEventListener(c[e],b,!1):a.detachEvent&&a.detachEvent("on"+c[e],b)},normalizeEvent:function(a){if(!a||!a.target)a=window.event,a.target=a.srcElement,a.stopPropagation=function(){this.cancelBubble=!0},a.preventDefault=function(){this.returnValue=!1};return a},createElement:function(a,c){var b=document.createElement(a);if(c)b.className=c;return b},setCSS:function(a,
c){if(a){var b=[],e={"line-height":1,"z-index":1,opacity:1},d;for(d in c)if(c.hasOwnProperty(d)){var f=d.replace(/([A-Z])/g,"-$1").toLowerCase(),g=c[d];b.push(f+":"+(typeof g=="number"&&!(f in e)?g+"px":g))}a.style.cssText+=";"+b.join(";")}},findNewlineBounds:function(a,c){for(var b=a.length,e=0,d=b-1,f=c-1;f>0;f--){var g=a.charAt(f);if(g=="\n"||g=="\r"){e=f+1;break}}for(f=c;f<b;f++)if(g=a.charAt(f),g=="\n"||g=="\r"){d=f;break}return{start:e,end:d}},sanitizeString:function(a){a=a.replace(/[<>&]/g,
function(a){return tx_utils.xml_chars[a]});return this.has_pre_wrap?a:a.replace(/\s/g,"&nbsp;"+this.line_breaker)},splitByLines:function(a,c){var b=(a||"").replace(/\r\n/g,"\n").replace(/\n\r/g,"\n").split("\n");if(c)for(var e=b.length;e>=0;e--)this.trim(b[e])||b.splice(e,1);return b},getLineNumber:function(a,c){for(var b=a.split(this.newline_char),e=0,d=this.newline_char.length,f=0,g=b.length;f<g;f++)if(e+=b[f].length,f<g-1&&(e+=d),c<e)return f;return-1},createElement:function(a,c){var b=document.createElement(a);
if(c)b.className=c;return b},toCamelCase:function(a){return a.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()})},getCSS:function(a,c,b){for(var e,d={},f,g,h=c instanceof Array,i=/^-?\d+(?:px)?$/i,j=/^-?\d(?:\.\d+)?/,l=/\d$/,k,o,p=h?c:[c],n=0,q=p.length;n<q;n++)if(f=p[n],g=this.toCamelCase(f),!b&&a.style[g])d[f]=d[g]=a.style[g];else if(this.use_w3c)e||(e=window.getComputedStyle(a,"")),d[f]=d[g]=e&&e.getPropertyValue(f);else if(a.currentStyle){k=a.currentStyle[f]||a.currentStyle[g];var m=a.style||
a;if(!i.test(k)&&j.test(k)){var r=m.left,s=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;o=l.test(k)?"em":"";m.left=g==="fontSize"?"1em":k+o||0;k=m.pixelLeft+"px";m.left=r;a.runtimeStyle.left=s}d[f]=d[g]=k}return h?d:d[this.toCamelCase(c)]},setCSS:function(a,c){if(a){var b=[],e={"line-height":1,"z-index":1,opacity:1},d;for(d in c)if(c.hasOwnProperty(d)){var f=d.replace(/([A-Z])/g,"-$1").toLowerCase(),g=c[d];b.push(f+":"+(typeof g=="number"&&!(f in e)?g+"px":g))}a.style.cssText+=";"+
b.join(";")}},createMeasurer:function(a){for(var c=this.createElement("div","tx-ca-measurer"),b=this.getCSS(a,this.copy_props),e=0;e<this.copy_props.length;e++){var d=this.copy_props[e];c.style[this.toCamelCase(d)]=b[d]}a.parentNode.appendChild(c);return c}};tx_utils.init();