<?php

class InitLogic extends SOY2LogicBase{

	function init(){
		
		if(isset($_POST["config_dir"])){
			$dir = soy2_realpath($_POST["config_dir"]);
			SOYCMSConfigUtil::put("config_dir",$dir);
			$db_dir = $dir . "/db/";
			if(!file_exists($db_dir) && !soy2_mkdir($db_dir))$db_dir = $dir;
			SOYCMSConfigUtil::put("db_dir",soy2_realpath($db_dir));
		}
		
		//初期化
		file_put_contents(SOYCMSConfigUtil::get("config_dir") . ".htaccess","deny from all");
		
		$res = $this->generateDBConfigFile();
		if(!$res)throw new Exception("Can not write db configure file to " . SOYCMSConfigUtil::get("config_dir"));
		
		$res = $this->generateUserConfigFile();
		if(!$res)throw new Exception("Can not write user configure file to " . SOYCMSConfigUtil::get("config_dir"));
		
		try{
			$res = $this->initDB();
			if(!$res)throw new Exception("failed initialize database");
		}catch(Exception $e){
			if(!$res)throw new Exception("failed initialize database");
		}
		
		try{
			$res = $this->initUser();
			if(!$res)throw new Exception("failed initialize administrator");
		}catch(Exception $e){
			if(!$res)throw new Exception("failed initialize administrator");
		}
		
		try{
			$serverConfig = @$_SESSION["soycms_init_server"];
			if($serverConfig){
				if(strlen($serverConfig->getFromMailAddress())<1){
					$serverConfig->setFromMailAddress(@$_POST["User"]["mailAddress"]);
					$serverConfig->setFromMailAddressName(@$_POST["User"]["userId"]);
				}
				
				
				$logic = SOY2Logic::createInstance("mail.SOYCMS_MailLogic");
				$logic->saveServerConfig($serverConfig);
				unset($_SESSION["soycms_init_server"]);
			}
		}catch(Exception $e){
			
		}
		
		return true;
		
	}

	/**
	 * DBを初期化
	 */
	function initDB(){

		//db.conf.phpのinclude
		include_once(SOYCMSConfigUtil::get("config_dir") . "db.conf.php");
		SOY2DAOConfig::Dsn(SOYCMS_DB_DSN);
		SOY2DAOConfig::user(SOYCMS_DB_USER);
		SOY2DAOConfig::password(SOYCMS_DB_PASS);
		
		//clear db
		if(SOYCMS_IS_DEBUG())unlink(str_replace("sqlite:","",SOYCMS_DB_DSN));

		$pdo = new SOY2DAO();
		$sql = file_get_contents(soy2_realpath(dirname(__FILE__)) . "admin.sql");
		$sqls = explode(";",$sql);

		foreach($sqls as $sql){
			try{
				if(empty($sql))continue;
				$pdo->executeUpdateQuery($sql,array());
			}catch(Exception $e){
				if(SOYCMS_IS_DEBUG())var_dump($e);
			}
		}

		return true;
	}
	
	/**
	 * 初期管理者の作成
	 */
	function initUser(){
		$user = $_POST["User"];
		$userId = $user["userId"];
		if(strlen($userId) < 1)$userId = "root";
		$password = $user["password"];
		if(strlen($password) < 1)$password = "password";
		
		SOY2::import("admin.domain.SOYCMS_User");
		$user = SOY2::cast("SOYCMS_User",$user);
		$user->setUserId($userId);
		$user->setPassword($user->hashPassword($password));
		$user->setLevel(0);
		$user->save();
		
		return true;
		
	}

	/**
	 * DB設定ファイルを出力
	 */
	function generateDBConfigFile(){

		$configpath = SOYCMSConfigUtil::get("config_dir") . "db.conf.php";

		$dbType = "sqlite";
		$dsn = "sqlite:" . SOYCMSConfigUtil::get("db_dir") . "admin.db";
		$user = "";
		$pass = "";


		$file = array();
		$file[] = '<?php';
		$file[] = '/* generated by SOYCMS ' . date("Y-m-d H:i:s") . ' */';

		//DB_TYPE
		$file[] = 'define("SOYCMS_DB_TYPE","'.$dbType.'");';
		$file[] = 'define("SOYCMS_DB_DSN","'.$dsn.'");';
		$file[] = 'define("SOYCMS_DB_USER","'.$user.'");';
		$file[] = 'define("SOYCMS_DB_PASS","'.$pass.'");';


		file_put_contents($configpath, implode("\n",$file));
	
		return true;
	}

	/**
	 * ユーザ設定ファイルを出力
	 */
	function generateUserConfigFile(){
		
		$configpath = SOYCMS_COMMON_DIR . "conf/user/user.conf.php";

		$file = array();
		$file[] = '<?php';
		$file[] = '/* generated by SOYCMS ' . date("Y-m-d H:i:s") . ' */';

		//DB_TYPE
		$file[] = 'SOYCMSConfigUtil::put("config_dir","'.SOYCMSConfigUtil::get("config_dir").'");';
		$file[] = 'SOYCMSConfigUtil::put("db_dir","'.SOYCMSConfigUtil::get("db_dir").'");';

		file_put_contents($configpath, implode("\n",$file));
		
		return true;
	}
}
?>